colorScheme = "slate"
footer.showAppearanceSwitcher = true
article.showAuthor = false

[list]
  showTableOfContents = false
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false

[homepage]
    showRecent = true
    layout = "page"
    recentLimit = 5
